# This is a TOML document.

startup_message = "Hi! This is a customized startup message"

[application]
    [live]
        port = "8080"
    [development]
        port = "8000"


[database]
host        = "localhost"
port        = "5432"
database    = "cars"
user        = "carsuser"
password    = "carspwd"

